### ISSUE TITLE
Problem with words like "night’s" causing keyphrases to be malformed due to ’ character

### ISSUE THREAD

**Issue by fmacdonald** [retextjs/retext-keywords#14]
Hi Guys,

hoping you can help me with an issue i'm having. I've created an example using the example code provided so the bug can be reproduced.

the issue is that when analysing text which contains words such as "night’s" e.g. :

"Last night’s concert was the third in a series organised by the Lizz Hobbs Group, who have now produced concerts at Slessor Gardens two years in a row."

the keyphrase is given as "Last night2’2s concert". I'm wondering how i can work around this or resolve so that the 2s are not appearing around the ’ character.

please see the following example code:

~~~~
var retext = require('retext');
var keywords = require('retext-keywords');
var nlcstToString = require('nlcst-to-string');

var text = "Last night’s concert was the third in a series organised by the Lizz Hobbs Group, who have now produced concerts at Slessor Gardens two years in a row.";

retext()
  .use(keywords)
  .process(text, function (err, file) {
    if (err) throw err;

    console.log('Keywords:');
    file.data.keywords.forEach(function (keyword) {
      console.log(nlcstToString(keyword.matches[0].node));
    });

    console.log();
    console.log('Key-phrases:');
    file.data.keyphrases.forEach(function (phrase) {
      console.log(phrase.matches[0].nodes.map(nlcstToString).join(''));
    });
  }
);
~~~~

output is:

~~~~
Keywords:
concert
Last
night’s
third
series
Lizz
Hobbs
Group
Slessor
Gardens
two
years
row

Key-phrases:
Last night2’2s concert
Slessor Gardens two years
Lizz Hobbs Group
concerts
~~~~

see **Last night2’2s concert**

node v10.10.0
npm 6.4.1

i'd appreciate any pointers as i'm not sure how to approach resolving the issue.

**Comment by fmacdonald** [comment]
the issue appears to occur during the mapping done by nlcstToString

**Comment by wooorm** [comment]
`nlcst-to-string` does accept a second argument, the `separator`, which is used to join stuff together.
This kind of looks like it could be accidentally passed by using `someWords.map(nlcstStoString)`, but I don’t think that happens here or in `retext-pos`? 🤔

**Comment by fmacdonald** [comment]
thanks for your tip @wooorm . I've found a workaround by using the `lodash` module `_.map` function - i'm not exactly sure why this works and the current method doesn't though 🙃.

please see the working example below:

```
var retext = require('retext');
var keywords = require('retext-keywords');
var nlcstToString = require('nlcst-to-string');
var _ = require('lodash');

var text = "Last night’s concert was the third in a series organised by the Lizz Hobbs Group, who have now produced concerts at Slessor Gardens two years in a row.";

retext()
  .use(keywords)
  .process(text, function (err, file) {
    if (err) throw err;

    console.log('Keywords:');
    file.data.keywords.forEach(function (keyword) {
      console.log(nlcstToString(keyword.matches[0].node));
    });

    console.log();
    console.log('Key-phrases:');
    file.data.keyphrases.forEach(function (phrase) {
      
      //console.log(phrase.matches[0].nodes.map(nlcstToString).join(''));

      var nodes = phrase.matches[0].nodes;
      tree = _.map(nodes);
      console.log(nlcstToString(tree, ""));
    });
  }
);
```

which gives as expected:

```
Keywords:
concert
Last
night’s
third
series
Lizz
Hobbs
Group
Slessor
Gardens
two
years
row

Key-phrases:
Last night’s concert
Slessor Gardens two years
Lizz Hobbs Group
concerts
```

**Comment by wooorm** [comment]
Ah, I fixed the example in the readme. Thanks!
