### ISSUE TITLE
What algorithm does this use?

### ISSUE THREAD

**Issue by Immortalin** [retextjs/retext-keywords#16]
Thanks for building this! Do you think you can put the underlying algorithm (RAKE?) in README for easier estimation of big-O?

**Comment by wooorm** [comment]
This algorithm is not modelled after something described in a paper, so I’m not sure what to put in the readme.
For performance, if we’re talking about Big-O, it’s probably slow!

**Comment by Immortalin** [comment]
Hmm is it feasible for e.g. real-time use? I.e. [something like this](https://immortalin.github.io/ai_notebook) where the entire text is re-evaluated everytime a user types.

**Comment by wooorm** [comment]
I don’t think any keyword extraction is fast enough to really do that. Maybe for one paragraph, but not if people are writing say a book.

This is outside of the scope of this project. But I find it pretty interesting, and what I’d attempt to do is do some change tracking: figure out which paragraph someone is working on and reevaluate that (throttled). Do the actual keyword detection in a web worker. Keep a list of keywords per paragraph. Show a view of the calculated top keywords for the whole document on the side!
