### ISSUE TITLE
Identify American English

### ISSUE THREAD

**Issue by adnansalehin** [retextjs/retext-keywords#17]
Keywords that are identified if written in en-uk are not identified if written in en-us.

Example: favourite is identified as a keyword, but favorite is not.

I tried out a few workarounds but didn't get anywhere. Please let me know if a workaround already exists.

**Comment by wooorm** [comment]
This is something for the deeper dependency [`pos`](https://github.com/dariusk/pos-js), if done there, it would also affect the library here.

Or you could alternatively preprocess the text by “Britishising” it? 🤷‍♂️
