### ISSUE TITLE
Phrases

### ISSUE THREAD

**Issue by btray77** [retextjs/retext-keywords#19]
### Subject of the feature

I have noticed a lot of single-word phrases are being returned in some documents.  Considering "phrases" is plural I think it should return 2+ word phrases.

### Problem

It would be nice to be able to select phrases by a number of words or greater than a specific number of words.

### Expected behavior

return "phases" not single words.  Preferably the ability to chose between 3-6 or 2-4 word phrases.

**Comment by wooorm** [comment]
Please fill out the issue template. It’s their for a reason.

**Comment by btray77** [comment]
updated to use template.

**Comment by wooorm** [comment]
Thanks for your patience and fixing the issue template!

I do feel like this is something you could do on your side: you get access to a list of stems, so you can ignore matches with one stem.

I’m not too sure if I agree on your assertion that “phrases” implies that 1 word cannot be a phrase: I think the inclusion of `terms` and `communities` in the readme example are correct, so I don’t think the default behavior should ignore 1-word phrases.

I’d be okay with the addition of this as an option if someone wants to work on a PR, but again I think it’s fine to do it in userland too

**Comment by wooorm** [comment]
Closing as explained in my previous comments!
