### ISSUE TITLE
Error: Attempted import error: 'color' is not exported from 'unist-util-visit-parents/do-not-use-color' (imported as 'color').

### ISSUE THREAD

**Issue by daveleee** [retextjs/retext-keywords#22]
### Initial checklist

- [X] I read the [support docs](https://github.com/retextjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/retextjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/retextjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aretextjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

     "retext": "^9.0.0",     "retext-keywords": "^8.0.1",     "retext-pos": "^5.0.0",    "nlcst-to-string": "^4.0.0",    "to-vfile": "^8.0.0",

### Steps to reproduce

1. Start a new Next.js (V13) project in a clean directory
2. pnpm install retext
3. pnpm install retext-keywords
4. pnpm install nlcst-to-string
5. pnpm install retext-pos
6. pnpm install to-vfile
7. create a file called index.tsx
8. copy the contents of the example given in the readme
9. create the example.txt file in the same directory
10. run app

### Expected behavior

We should be able to see keywords and phrases, but instead, we encounter the following error:

./node_modules/.pnpm/unist-util-visit-parents@6.0.1/node_modules/unist-util-visit-parents/lib/index.js
Attempted import error: 'color' is not exported from 'unist-util-visit-parents/do-not-use-color' (imported as 'color').

![image](https://github.com/retextjs/retext-keywords/assets/18183671/966fd1d7-839f-4a46-bc96-ea82b8f8d0dc)
![image](https://github.com/retextjs/retext-keywords/assets/18183671/ed254a0d-8539-4e70-901a-e42294c7b43c)

### Affected runtime and version

node@18.16.0

### Affected package manager and version

pnpm@8.11.0

### Affected OS and version

MacOS Sonoma 14.1.2

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
welcome @daveleee! 👋 
Sorry you ran into a spot of trouble.

I can't replicate the issue with the steps you provided.
It works fine https://stackblitz.com/edit/stackblitz-starters-j7cta1?file=app%2Fpage.tsx
You most likely have a misconfigured Next.js instance or are experiencing a bug with pnpm.

**Comment by macs1756** [comment]
Just install your dependencies via yarn — it works for me.
